---
- name: Install service
  tags:
    - services
  become: true
  ansible.builtin.apt:
    name: "{{ service_details.value.package }}"
    state: present
  loop: "{{ services | default({}) | dict2items }}"
  loop_control:
    label: "{{ service_details.key }}"
    loop_var: service_details

- name: Deploy and manage services
  tags: services
  loop: "{{ services | default({}) | dict2items }}"
  loop_control:
    label: "{{ current_service_details.key }}"
    loop_var: current_service_details
  ansible.builtin.include_tasks: manage-service.yml
