# vim: set filetype=yaml.ansible:
---
- name: Restart services
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  listen: "restart services"
  loop: "{{ services.keys() | list }}"
  become: true
