# vim: set filetype=yaml.ansible:
---
- name: RESTART SERVICES
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  listen: "restart services"
  loop: "{{ services_to_restart }}"
  become: true
